# Generated by Django 5.1.1 on 2026-01-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="rag_files/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("total_documents", models.IntegerField(default=0)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="query",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="document",
            name="char_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="chunk_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_json",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="document",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="query",
            name="embedding_json",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="query",
            name="relevant_documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="rag.file",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file", "chunk_index"], name="rag_documen_file_id_0f9460_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["-created_at"], name="rag_documen_created_393bf5_idx"
            ),
        ),
    ]
